[package]
name = "fadupes"
version = "0.0.2"
edition = "2021"

[dependencies]
walkdir = "2"
crc32fast = "1.3.2"
claxon = "0.4.3"
tracing = "0.1.37"
clap = {version = "4.3.19", features = ["cargo"]}
hound = "3.5.1"
rayon = "1.10.0"

[[bin]]
name = "fadupes"
path = "src/bin/main.rs"
